threshold:
  min_confidence: 0.0
  ambiguity_delta: 0.0

intents:
  - name: request_operator
    rules:
      - type: keyword
        weight: 1.0
        values:
          [
            "оператор",
            "человек",
            "живой",
            "позвать",
            "не_бот",
          ]
      - type: phrase
        weight: 3.0
        values:
          [
            "говорить_оператор",
            "связаться с оператором",
            "поговорить с человеком",
            "связаться с живым человеком",
            "поговорить с живым человеком",
            "позовите оператора",
            "позовите человека",
            "позовите живого человека",
            "не хочу говорить с ботом",
            "не бот",
            "нужен человек",
          ]