// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActions = `-- name: CountActions :one
SELECT COUNT(*)::BIGINT FROM actions_log
WHERE "session_id" = $1::UUID
`

func (q *Queries) CountActions(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActions, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getActionsBySessionID = `-- name: GetActionsBySessionID :many
SELECT id, session_id, action_type, request_payload, response_payload, error, created_at FROM actions_log
WHERE "session_id" = $1::UUID
ORDER BY "created_at" DESC
LIMIT $2::INT OFFSET $3::INT
`

type GetActionsBySessionIDParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 int32       `json:"column_2"`
	Column3 int32       `json:"column_3"`
}

func (q *Queries) GetActionsBySessionID(ctx context.Context, arg GetActionsBySessionIDParams) ([]ActionsLog, error) {
	rows, err := q.db.Query(ctx, getActionsBySessionID, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionsLog{}
	for rows.Next() {
		var i ActionsLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ActionType,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActionsByType = `-- name: GetActionsByType :many
SELECT id, session_id, action_type, request_payload, response_payload, error, created_at FROM actions_log
WHERE "action_type" = $1::VARCHAR(50)
ORDER BY "created_at" DESC
LIMIT $2::INT OFFSET $3::INT
`

type GetActionsByTypeParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
}

func (q *Queries) GetActionsByType(ctx context.Context, arg GetActionsByTypeParams) ([]ActionsLog, error) {
	rows, err := q.db.Query(ctx, getActionsByType, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionsLog{}
	for rows.Next() {
		var i ActionsLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ActionType,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAction = `-- name: LogAction :one
INSERT INTO actions_log ("session_id", "action_type", "request_payload", "response_payload", "error")
VALUES ($1::UUID, $2::VARCHAR(50), $3::JSONB, $4::JSONB, $5::TEXT)
RETURNING id, session_id, action_type, request_payload, response_payload, error, created_at
`

type LogActionParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 []byte      `json:"column_3"`
	Column4 []byte      `json:"column_4"`
	Column5 string      `json:"column_5"`
}

func (q *Queries) LogAction(ctx context.Context, arg LogActionParams) (ActionsLog, error) {
	row := q.db.QueryRow(ctx, logAction,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i ActionsLog
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ActionType,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}
