// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brd_catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessageEvent = `-- name: CreateMessageEvent :one
INSERT INTO message_events (
    session_id,
    message_id,
    channel,
    external_event_id,
    event_type,
    payload,
    processed_at
)
VALUES (
    $1::UUID,
    $2::UUID,
    $3::TEXT,
    $4::TEXT,
    $5::VARCHAR(40),
    $6::JSONB,
    $7::TIMESTAMP
)
RETURNING id, session_id, message_id, channel, external_event_id, event_type, payload, received_at, processed_at
`

type CreateMessageEventParams struct {
	SessionID       pgtype.UUID      `json:"session_id"`
	MessageID       pgtype.UUID      `json:"message_id"`
	Channel         string           `json:"channel"`
	ExternalEventID string           `json:"external_event_id"`
	EventType       string           `json:"event_type"`
	Payload         []byte           `json:"payload"`
	ProcessedAt     pgtype.Timestamp `json:"processed_at"`
}

func (q *Queries) CreateMessageEvent(ctx context.Context, arg CreateMessageEventParams) (MessageEvent, error) {
	row := q.db.QueryRow(ctx, createMessageEvent,
		arg.SessionID,
		arg.MessageID,
		arg.Channel,
		arg.ExternalEventID,
		arg.EventType,
		arg.Payload,
		arg.ProcessedAt,
	)
	var i MessageEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.Channel,
		&i.ExternalEventID,
		&i.EventType,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const findDemoAccountByIdentifier = `-- name: FindDemoAccountByIdentifier :one
SELECT id, user_id, identifiers, email, phone, status, payload, created_at, updated_at FROM demo_accounts
WHERE $1::TEXT = user_id
   OR $1::TEXT = ANY(identifiers)
LIMIT 1
`

func (q *Queries) FindDemoAccountByIdentifier(ctx context.Context, identifier string) (DemoAccount, error) {
	row := q.db.QueryRow(ctx, findDemoAccountByIdentifier, identifier)
	var i DemoAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Identifiers,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDemoBookingByIdentifier = `-- name: FindDemoBookingByIdentifier :one
SELECT id, booking_number, identifiers, service, master, booking_date, booking_time, status, payload, created_at, updated_at FROM demo_bookings
WHERE $1::TEXT = booking_number
   OR $1::TEXT = ANY(identifiers)
LIMIT 1
`

func (q *Queries) FindDemoBookingByIdentifier(ctx context.Context, identifier string) (DemoBooking, error) {
	row := q.db.QueryRow(ctx, findDemoBookingByIdentifier, identifier)
	var i DemoBooking
	err := row.Scan(
		&i.ID,
		&i.BookingNumber,
		&i.Identifiers,
		&i.Service,
		&i.Master,
		&i.BookingDate,
		&i.BookingTime,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDemoPaymentByIdentifier = `-- name: FindDemoPaymentByIdentifier :one
SELECT id, payment_id, identifiers, amount_cents, paid_at, status, purpose, payload, created_at, updated_at FROM demo_payments
WHERE $1::TEXT = payment_id
   OR $1::TEXT = ANY(identifiers)
LIMIT 1
`

func (q *Queries) FindDemoPaymentByIdentifier(ctx context.Context, identifier string) (DemoPayment, error) {
	row := q.db.QueryRow(ctx, findDemoPaymentByIdentifier, identifier)
	var i DemoPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Identifiers,
		&i.AmountCents,
		&i.PaidAt,
		&i.Status,
		&i.Purpose,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDemoWorkspaceBookingByIdentifier = `-- name: FindDemoWorkspaceBookingByIdentifier :one
SELECT id, booking_number, identifiers, workspace_type, booking_date, booking_time, duration_hours, status, payload, created_at, updated_at FROM demo_workspace_bookings
WHERE $1::TEXT = booking_number
   OR $1::TEXT = ANY(identifiers)
LIMIT 1
`

func (q *Queries) FindDemoWorkspaceBookingByIdentifier(ctx context.Context, identifier string) (DemoWorkspaceBooking, error) {
	row := q.db.QueryRow(ctx, findDemoWorkspaceBookingByIdentifier, identifier)
	var i DemoWorkspaceBooking
	err := row.Scan(
		&i.ID,
		&i.BookingNumber,
		&i.Identifiers,
		&i.WorkspaceType,
		&i.BookingDate,
		&i.BookingTime,
		&i.DurationHours,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntentByKey = `-- name: GetIntentByKey :one
SELECT id, key, category, response_key, requires_action, escalate_on_failure, fallback_policy, active, metadata, created_at, updated_at FROM intents
WHERE key = $1::VARCHAR(80)
`

func (q *Queries) GetIntentByKey(ctx context.Context, dollar_1 string) (Intent, error) {
	row := q.db.QueryRow(ctx, getIntentByKey, dollar_1)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Category,
		&i.ResponseKey,
		&i.RequiresAction,
		&i.EscalateOnFailure,
		&i.FallbackPolicy,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageEventByExternalID = `-- name: GetMessageEventByExternalID :one
SELECT id, session_id, message_id, channel, external_event_id, event_type, payload, received_at, processed_at FROM message_events
WHERE channel = $1::TEXT
  AND external_event_id = $2::TEXT
`

type GetMessageEventByExternalIDParams struct {
	Channel         string `json:"channel"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetMessageEventByExternalID(ctx context.Context, arg GetMessageEventByExternalIDParams) (MessageEvent, error) {
	row := q.db.QueryRow(ctx, getMessageEventByExternalID, arg.Channel, arg.ExternalEventID)
	var i MessageEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.Channel,
		&i.ExternalEventID,
		&i.EventType,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getSessionContext = `-- name: GetSessionContext :one
SELECT session_id, active_topic, mode, last_intent, fallback_count, operator_status, metadata, version, created_at, updated_at FROM session_context
WHERE session_id = $1::UUID
`

func (q *Queries) GetSessionContext(ctx context.Context, dollar_1 pgtype.UUID) (SessionContext, error) {
	row := q.db.QueryRow(ctx, getSessionContext, dollar_1)
	var i SessionContext
	err := row.Scan(
		&i.SessionID,
		&i.ActiveTopic,
		&i.Mode,
		&i.LastIntent,
		&i.FallbackCount,
		&i.OperatorStatus,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveIntents = `-- name: ListActiveIntents :many
SELECT id, key, category, response_key, requires_action, escalate_on_failure, fallback_policy, active, metadata, created_at, updated_at FROM intents
WHERE active = true
ORDER BY category, key
`

func (q *Queries) ListActiveIntents(ctx context.Context) ([]Intent, error) {
	rows, err := q.db.Query(ctx, listActiveIntents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Intent{}
	for rows.Next() {
		var i Intent
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Category,
			&i.ResponseKey,
			&i.RequiresAction,
			&i.EscalateOnFailure,
			&i.FallbackPolicy,
			&i.Active,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionCandidates = `-- name: ListDecisionCandidates :many
SELECT id, decision_log_id, intent_id, intent_key, confidence, rank, source, metadata, created_at FROM decision_candidates
WHERE decision_log_id = $1::UUID
ORDER BY rank
`

func (q *Queries) ListDecisionCandidates(ctx context.Context, dollar_1 pgtype.UUID) ([]DecisionCandidate, error) {
	rows, err := q.db.Query(ctx, listDecisionCandidates, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DecisionCandidate{}
	for rows.Next() {
		var i DecisionCandidate
		if err := rows.Scan(
			&i.ID,
			&i.DecisionLogID,
			&i.IntentID,
			&i.IntentKey,
			&i.Confidence,
			&i.Rank,
			&i.Source,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuickRepliesByIntent = `-- name: ListQuickRepliesByIntent :many
SELECT id, intent_id, response_key, label, action, payload, sort_order, active, created_at, updated_at FROM quick_replies
WHERE intent_id = $1::UUID
  AND active = true
ORDER BY sort_order, label
`

func (q *Queries) ListQuickRepliesByIntent(ctx context.Context, dollar_1 pgtype.UUID) ([]QuickReply, error) {
	rows, err := q.db.Query(ctx, listQuickRepliesByIntent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuickReply{}
	for rows.Next() {
		var i QuickReply
		if err := rows.Scan(
			&i.ID,
			&i.IntentID,
			&i.ResponseKey,
			&i.Label,
			&i.Action,
			&i.Payload,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuickRepliesByResponseKey = `-- name: ListQuickRepliesByResponseKey :many
SELECT id, intent_id, response_key, label, action, payload, sort_order, active, created_at, updated_at FROM quick_replies
WHERE response_key = $1::VARCHAR(80)
  AND active = true
ORDER BY sort_order, label
`

func (q *Queries) ListQuickRepliesByResponseKey(ctx context.Context, dollar_1 string) ([]QuickReply, error) {
	rows, err := q.db.Query(ctx, listQuickRepliesByResponseKey, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QuickReply{}
	for rows.Next() {
		var i QuickReply
		if err := rows.Scan(
			&i.ID,
			&i.IntentID,
			&i.ResponseKey,
			&i.Label,
			&i.Action,
			&i.Payload,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logDecisionCandidate = `-- name: LogDecisionCandidate :one
INSERT INTO decision_candidates (
    decision_log_id,
    intent_id,
    intent_key,
    confidence,
    rank,
    source,
    metadata
)
VALUES (
    $1::UUID,
    $2::UUID,
    $3::VARCHAR(80),
    $4::DOUBLE PRECISION,
    $5::INT,
    $6::VARCHAR(32),
    $7::JSONB
)
RETURNING id, decision_log_id, intent_id, intent_key, confidence, rank, source, metadata, created_at
`

type LogDecisionCandidateParams struct {
	DecisionLogID pgtype.UUID `json:"decision_log_id"`
	IntentID      pgtype.UUID `json:"intent_id"`
	IntentKey     string      `json:"intent_key"`
	Confidence    float64     `json:"confidence"`
	Rank          int32       `json:"rank"`
	Source        string      `json:"source"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) LogDecisionCandidate(ctx context.Context, arg LogDecisionCandidateParams) (DecisionCandidate, error) {
	row := q.db.QueryRow(ctx, logDecisionCandidate,
		arg.DecisionLogID,
		arg.IntentID,
		arg.IntentKey,
		arg.Confidence,
		arg.Rank,
		arg.Source,
		arg.Metadata,
	)
	var i DecisionCandidate
	err := row.Scan(
		&i.ID,
		&i.DecisionLogID,
		&i.IntentID,
		&i.IntentKey,
		&i.Confidence,
		&i.Rank,
		&i.Source,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const searchIntentExamples = `-- name: SearchIntentExamples :many
SELECT
    intent_examples.id,
    intent_examples.intent_id,
    intents.key AS intent_key,
    intents.category,
    intents.response_key,
    intent_examples.text,
    intent_examples.normalized_text,
    intent_examples.locale,
    intent_examples.weight,
    (1 - (intent_examples.embedding <=> ($1::TEXT)::vector))::DOUBLE PRECISION AS confidence
FROM intent_examples
JOIN intents ON intents.id = intent_examples.intent_id
WHERE intent_examples.active = true
  AND intents.active = true
  AND intent_examples.locale = $2::VARCHAR(8)
ORDER BY intent_examples.embedding <=> ($1::TEXT)::vector
LIMIT $3::INT
`

type SearchIntentExamplesParams struct {
	Embedding   string `json:"embedding"`
	Locale      string `json:"locale"`
	ResultLimit int32  `json:"result_limit"`
}

type SearchIntentExamplesRow struct {
	ID             pgtype.UUID `json:"id"`
	IntentID       pgtype.UUID `json:"intent_id"`
	IntentKey      string      `json:"intent_key"`
	Category       string      `json:"category"`
	ResponseKey    string      `json:"response_key"`
	Text           string      `json:"text"`
	NormalizedText string      `json:"normalized_text"`
	Locale         string      `json:"locale"`
	Weight         float64     `json:"weight"`
	Confidence     float64     `json:"confidence"`
}

func (q *Queries) SearchIntentExamples(ctx context.Context, arg SearchIntentExamplesParams) ([]SearchIntentExamplesRow, error) {
	rows, err := q.db.Query(ctx, searchIntentExamples, arg.Embedding, arg.Locale, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchIntentExamplesRow{}
	for rows.Next() {
		var i SearchIntentExamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.IntentID,
			&i.IntentKey,
			&i.Category,
			&i.ResponseKey,
			&i.Text,
			&i.NormalizedText,
			&i.Locale,
			&i.Weight,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKnowledgeChunks = `-- name: SearchKnowledgeChunks :many
SELECT
    knowledge_chunks.id,
    knowledge_chunks.article_id,
    knowledge_articles.key AS article_key,
    knowledge_articles.category,
    knowledge_articles.title,
    knowledge_chunks.chunk_index,
    knowledge_chunks.body,
    (1 - (knowledge_chunks.embedding <=> ($1::TEXT)::vector))::DOUBLE PRECISION AS confidence
FROM knowledge_chunks
JOIN knowledge_articles ON knowledge_articles.id = knowledge_chunks.article_id
WHERE knowledge_chunks.active = true
  AND knowledge_articles.active = true
ORDER BY knowledge_chunks.embedding <=> ($1::TEXT)::vector
LIMIT $2::INT
`

type SearchKnowledgeChunksParams struct {
	Embedding   string `json:"embedding"`
	ResultLimit int32  `json:"result_limit"`
}

type SearchKnowledgeChunksRow struct {
	ID         pgtype.UUID `json:"id"`
	ArticleID  pgtype.UUID `json:"article_id"`
	ArticleKey string      `json:"article_key"`
	Category   string      `json:"category"`
	Title      string      `json:"title"`
	ChunkIndex int32       `json:"chunk_index"`
	Body       string      `json:"body"`
	Confidence float64     `json:"confidence"`
}

func (q *Queries) SearchKnowledgeChunks(ctx context.Context, arg SearchKnowledgeChunksParams) ([]SearchKnowledgeChunksRow, error) {
	rows, err := q.db.Query(ctx, searchKnowledgeChunks, arg.Embedding, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchKnowledgeChunksRow{}
	for rows.Next() {
		var i SearchKnowledgeChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.ArticleKey,
			&i.Category,
			&i.Title,
			&i.ChunkIndex,
			&i.Body,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDemoAccount = `-- name: UpsertDemoAccount :one
INSERT INTO demo_accounts (id, user_id, identifiers, email, phone, status, payload)
VALUES (
    $1::TEXT,
    $2::TEXT,
    $3::TEXT[],
    $4::TEXT,
    $5::TEXT,
    $6::VARCHAR(32),
    $7::JSONB
)
ON CONFLICT (id) DO UPDATE
SET user_id = EXCLUDED.user_id,
    identifiers = EXCLUDED.identifiers,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    status = EXCLUDED.status,
    payload = EXCLUDED.payload,
    updated_at = now()
RETURNING id, user_id, identifiers, email, phone, status, payload, created_at, updated_at
`

type UpsertDemoAccountParams struct {
	ID          string   `json:"id"`
	UserID      string   `json:"user_id"`
	Identifiers []string `json:"identifiers"`
	Email       string   `json:"email"`
	Phone       string   `json:"phone"`
	Status      string   `json:"status"`
	Payload     []byte   `json:"payload"`
}

func (q *Queries) UpsertDemoAccount(ctx context.Context, arg UpsertDemoAccountParams) (DemoAccount, error) {
	row := q.db.QueryRow(ctx, upsertDemoAccount,
		arg.ID,
		arg.UserID,
		arg.Identifiers,
		arg.Email,
		arg.Phone,
		arg.Status,
		arg.Payload,
	)
	var i DemoAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Identifiers,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDemoBooking = `-- name: UpsertDemoBooking :one
INSERT INTO demo_bookings (
    id,
    booking_number,
    identifiers,
    service,
    master,
    booking_date,
    booking_time,
    status,
    payload
)
VALUES (
    $1::TEXT,
    $2::TEXT,
    $3::TEXT[],
    $4::TEXT,
    $5::TEXT,
    $6::DATE,
    $7::TIME,
    $8::VARCHAR(32),
    $9::JSONB
)
ON CONFLICT (id) DO UPDATE
SET booking_number = EXCLUDED.booking_number,
    identifiers = EXCLUDED.identifiers,
    service = EXCLUDED.service,
    master = EXCLUDED.master,
    booking_date = EXCLUDED.booking_date,
    booking_time = EXCLUDED.booking_time,
    status = EXCLUDED.status,
    payload = EXCLUDED.payload,
    updated_at = now()
RETURNING id, booking_number, identifiers, service, master, booking_date, booking_time, status, payload, created_at, updated_at
`

type UpsertDemoBookingParams struct {
	ID            string      `json:"id"`
	BookingNumber string      `json:"booking_number"`
	Identifiers   []string    `json:"identifiers"`
	Service       string      `json:"service"`
	Master        string      `json:"master"`
	BookingDate   pgtype.Date `json:"booking_date"`
	BookingTime   pgtype.Time `json:"booking_time"`
	Status        string      `json:"status"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) UpsertDemoBooking(ctx context.Context, arg UpsertDemoBookingParams) (DemoBooking, error) {
	row := q.db.QueryRow(ctx, upsertDemoBooking,
		arg.ID,
		arg.BookingNumber,
		arg.Identifiers,
		arg.Service,
		arg.Master,
		arg.BookingDate,
		arg.BookingTime,
		arg.Status,
		arg.Payload,
	)
	var i DemoBooking
	err := row.Scan(
		&i.ID,
		&i.BookingNumber,
		&i.Identifiers,
		&i.Service,
		&i.Master,
		&i.BookingDate,
		&i.BookingTime,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDemoPayment = `-- name: UpsertDemoPayment :one
INSERT INTO demo_payments (
    id,
    payment_id,
    identifiers,
    amount_cents,
    paid_at,
    status,
    purpose,
    payload
)
VALUES (
    $1::TEXT,
    $2::TEXT,
    $3::TEXT[],
    $4::INT,
    $5::TIMESTAMPTZ,
    $6::VARCHAR(32),
    $7::TEXT,
    $8::JSONB
)
ON CONFLICT (id) DO UPDATE
SET payment_id = EXCLUDED.payment_id,
    identifiers = EXCLUDED.identifiers,
    amount_cents = EXCLUDED.amount_cents,
    paid_at = EXCLUDED.paid_at,
    status = EXCLUDED.status,
    purpose = EXCLUDED.purpose,
    payload = EXCLUDED.payload,
    updated_at = now()
RETURNING id, payment_id, identifiers, amount_cents, paid_at, status, purpose, payload, created_at, updated_at
`

type UpsertDemoPaymentParams struct {
	ID          string             `json:"id"`
	PaymentID   string             `json:"payment_id"`
	Identifiers []string           `json:"identifiers"`
	AmountCents int32              `json:"amount_cents"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	Status      string             `json:"status"`
	Purpose     string             `json:"purpose"`
	Payload     []byte             `json:"payload"`
}

func (q *Queries) UpsertDemoPayment(ctx context.Context, arg UpsertDemoPaymentParams) (DemoPayment, error) {
	row := q.db.QueryRow(ctx, upsertDemoPayment,
		arg.ID,
		arg.PaymentID,
		arg.Identifiers,
		arg.AmountCents,
		arg.PaidAt,
		arg.Status,
		arg.Purpose,
		arg.Payload,
	)
	var i DemoPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Identifiers,
		&i.AmountCents,
		&i.PaidAt,
		&i.Status,
		&i.Purpose,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDemoWorkspaceBooking = `-- name: UpsertDemoWorkspaceBooking :one
INSERT INTO demo_workspace_bookings (
    id,
    booking_number,
    identifiers,
    workspace_type,
    booking_date,
    booking_time,
    duration_hours,
    status,
    payload
)
VALUES (
    $1::TEXT,
    $2::TEXT,
    $3::TEXT[],
    $4::TEXT,
    $5::DATE,
    $6::TIME,
    $7::INT,
    $8::VARCHAR(32),
    $9::JSONB
)
ON CONFLICT (id) DO UPDATE
SET booking_number = EXCLUDED.booking_number,
    identifiers = EXCLUDED.identifiers,
    workspace_type = EXCLUDED.workspace_type,
    booking_date = EXCLUDED.booking_date,
    booking_time = EXCLUDED.booking_time,
    duration_hours = EXCLUDED.duration_hours,
    status = EXCLUDED.status,
    payload = EXCLUDED.payload,
    updated_at = now()
RETURNING id, booking_number, identifiers, workspace_type, booking_date, booking_time, duration_hours, status, payload, created_at, updated_at
`

type UpsertDemoWorkspaceBookingParams struct {
	ID            string      `json:"id"`
	BookingNumber string      `json:"booking_number"`
	Identifiers   []string    `json:"identifiers"`
	WorkspaceType string      `json:"workspace_type"`
	BookingDate   pgtype.Date `json:"booking_date"`
	BookingTime   pgtype.Time `json:"booking_time"`
	DurationHours *int32      `json:"duration_hours"`
	Status        string      `json:"status"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) UpsertDemoWorkspaceBooking(ctx context.Context, arg UpsertDemoWorkspaceBookingParams) (DemoWorkspaceBooking, error) {
	row := q.db.QueryRow(ctx, upsertDemoWorkspaceBooking,
		arg.ID,
		arg.BookingNumber,
		arg.Identifiers,
		arg.WorkspaceType,
		arg.BookingDate,
		arg.BookingTime,
		arg.DurationHours,
		arg.Status,
		arg.Payload,
	)
	var i DemoWorkspaceBooking
	err := row.Scan(
		&i.ID,
		&i.BookingNumber,
		&i.Identifiers,
		&i.WorkspaceType,
		&i.BookingDate,
		&i.BookingTime,
		&i.DurationHours,
		&i.Status,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIntent = `-- name: UpsertIntent :one
INSERT INTO intents (
    key,
    category,
    response_key,
    requires_action,
    escalate_on_failure,
    fallback_policy,
    active,
    metadata
)
VALUES (
    $1::VARCHAR(80),
    $2::VARCHAR(80),
    $3::VARCHAR(80),
    $4::BOOLEAN,
    $5::BOOLEAN,
    $6::VARCHAR(32),
    $7::BOOLEAN,
    $8::JSONB
)
ON CONFLICT (key) DO UPDATE
SET category = EXCLUDED.category,
    response_key = EXCLUDED.response_key,
    requires_action = EXCLUDED.requires_action,
    escalate_on_failure = EXCLUDED.escalate_on_failure,
    fallback_policy = EXCLUDED.fallback_policy,
    active = EXCLUDED.active,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, key, category, response_key, requires_action, escalate_on_failure, fallback_policy, active, metadata, created_at, updated_at
`

type UpsertIntentParams struct {
	Key               string `json:"key"`
	Category          string `json:"category"`
	ResponseKey       string `json:"response_key"`
	RequiresAction    bool   `json:"requires_action"`
	EscalateOnFailure bool   `json:"escalate_on_failure"`
	FallbackPolicy    string `json:"fallback_policy"`
	Active            bool   `json:"active"`
	Metadata          []byte `json:"metadata"`
}

func (q *Queries) UpsertIntent(ctx context.Context, arg UpsertIntentParams) (Intent, error) {
	row := q.db.QueryRow(ctx, upsertIntent,
		arg.Key,
		arg.Category,
		arg.ResponseKey,
		arg.RequiresAction,
		arg.EscalateOnFailure,
		arg.FallbackPolicy,
		arg.Active,
		arg.Metadata,
	)
	var i Intent
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Category,
		&i.ResponseKey,
		&i.RequiresAction,
		&i.EscalateOnFailure,
		&i.FallbackPolicy,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIntentExample = `-- name: UpsertIntentExample :one
INSERT INTO intent_examples (
    intent_id,
    text,
    normalized_text,
    embedding,
    locale,
    weight,
    active,
    metadata
)
VALUES (
    $1::UUID,
    $2::TEXT,
    $3::TEXT,
    ($4::TEXT)::vector,
    $5::VARCHAR(8),
    $6::DOUBLE PRECISION,
    $7::BOOLEAN,
    $8::JSONB
)
ON CONFLICT (intent_id, locale, normalized_text) DO UPDATE
SET text = EXCLUDED.text,
    embedding = EXCLUDED.embedding,
    weight = EXCLUDED.weight,
    active = EXCLUDED.active,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, intent_id, text, normalized_text, locale, weight, active, metadata, created_at, updated_at
`

type UpsertIntentExampleParams struct {
	IntentID       pgtype.UUID `json:"intent_id"`
	Text           string      `json:"text"`
	NormalizedText string      `json:"normalized_text"`
	Embedding      string      `json:"embedding"`
	Locale         string      `json:"locale"`
	Weight         float64     `json:"weight"`
	Active         bool        `json:"active"`
	Metadata       []byte      `json:"metadata"`
}

type UpsertIntentExampleRow struct {
	ID             pgtype.UUID      `json:"id"`
	IntentID       pgtype.UUID      `json:"intent_id"`
	Text           string           `json:"text"`
	NormalizedText string           `json:"normalized_text"`
	Locale         string           `json:"locale"`
	Weight         float64          `json:"weight"`
	Active         bool             `json:"active"`
	Metadata       []byte           `json:"metadata"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertIntentExample(ctx context.Context, arg UpsertIntentExampleParams) (UpsertIntentExampleRow, error) {
	row := q.db.QueryRow(ctx, upsertIntentExample,
		arg.IntentID,
		arg.Text,
		arg.NormalizedText,
		arg.Embedding,
		arg.Locale,
		arg.Weight,
		arg.Active,
		arg.Metadata,
	)
	var i UpsertIntentExampleRow
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.Text,
		&i.NormalizedText,
		&i.Locale,
		&i.Weight,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKnowledgeArticle = `-- name: UpsertKnowledgeArticle :one
INSERT INTO knowledge_articles (
    key,
    category,
    title,
    body,
    source,
    active,
    metadata
)
VALUES (
    $1::VARCHAR(120),
    $2::VARCHAR(80),
    $3::TEXT,
    $4::TEXT,
    $5::TEXT,
    $6::BOOLEAN,
    $7::JSONB
)
ON CONFLICT (key) DO UPDATE
SET category = EXCLUDED.category,
    title = EXCLUDED.title,
    body = EXCLUDED.body,
    source = EXCLUDED.source,
    active = EXCLUDED.active,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, key, category, title, body, source, active, metadata, created_at, updated_at
`

type UpsertKnowledgeArticleParams struct {
	Key      string `json:"key"`
	Category string `json:"category"`
	Title    string `json:"title"`
	Body     string `json:"body"`
	Source   string `json:"source"`
	Active   bool   `json:"active"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) UpsertKnowledgeArticle(ctx context.Context, arg UpsertKnowledgeArticleParams) (KnowledgeArticle, error) {
	row := q.db.QueryRow(ctx, upsertKnowledgeArticle,
		arg.Key,
		arg.Category,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.Active,
		arg.Metadata,
	)
	var i KnowledgeArticle
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Category,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKnowledgeChunk = `-- name: UpsertKnowledgeChunk :one
INSERT INTO knowledge_chunks (
    article_id,
    chunk_index,
    body,
    embedding,
    active,
    metadata
)
VALUES (
    $1::UUID,
    $2::INT,
    $3::TEXT,
    ($4::TEXT)::vector,
    $5::BOOLEAN,
    $6::JSONB
)
ON CONFLICT (article_id, chunk_index) DO UPDATE
SET body = EXCLUDED.body,
    embedding = EXCLUDED.embedding,
    active = EXCLUDED.active,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, article_id, chunk_index, body, active, metadata, created_at, updated_at
`

type UpsertKnowledgeChunkParams struct {
	ArticleID  pgtype.UUID `json:"article_id"`
	ChunkIndex int32       `json:"chunk_index"`
	Body       string      `json:"body"`
	Embedding  string      `json:"embedding"`
	Active     bool        `json:"active"`
	Metadata   []byte      `json:"metadata"`
}

type UpsertKnowledgeChunkRow struct {
	ID         pgtype.UUID      `json:"id"`
	ArticleID  pgtype.UUID      `json:"article_id"`
	ChunkIndex int32            `json:"chunk_index"`
	Body       string           `json:"body"`
	Active     bool             `json:"active"`
	Metadata   []byte           `json:"metadata"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertKnowledgeChunk(ctx context.Context, arg UpsertKnowledgeChunkParams) (UpsertKnowledgeChunkRow, error) {
	row := q.db.QueryRow(ctx, upsertKnowledgeChunk,
		arg.ArticleID,
		arg.ChunkIndex,
		arg.Body,
		arg.Embedding,
		arg.Active,
		arg.Metadata,
	)
	var i UpsertKnowledgeChunkRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.ChunkIndex,
		&i.Body,
		&i.Active,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertQuickReply = `-- name: UpsertQuickReply :one
INSERT INTO quick_replies (
    intent_id,
    response_key,
    label,
    action,
    payload,
    sort_order,
    active
)
VALUES (
    $1::UUID,
    $2::VARCHAR(80),
    $3::TEXT,
    $4::VARCHAR(40),
    $5::JSONB,
    $6::INT,
    $7::BOOLEAN
)
RETURNING id, intent_id, response_key, label, action, payload, sort_order, active, created_at, updated_at
`

type UpsertQuickReplyParams struct {
	IntentID    pgtype.UUID `json:"intent_id"`
	ResponseKey string      `json:"response_key"`
	Label       string      `json:"label"`
	Action      string      `json:"action"`
	Payload     []byte      `json:"payload"`
	SortOrder   int32       `json:"sort_order"`
	Active      bool        `json:"active"`
}

func (q *Queries) UpsertQuickReply(ctx context.Context, arg UpsertQuickReplyParams) (QuickReply, error) {
	row := q.db.QueryRow(ctx, upsertQuickReply,
		arg.IntentID,
		arg.ResponseKey,
		arg.Label,
		arg.Action,
		arg.Payload,
		arg.SortOrder,
		arg.Active,
	)
	var i QuickReply
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.ResponseKey,
		&i.Label,
		&i.Action,
		&i.Payload,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSessionContext = `-- name: UpsertSessionContext :one
INSERT INTO session_context (
    session_id,
    active_topic,
    mode,
    last_intent,
    fallback_count,
    operator_status,
    metadata,
    version
)
VALUES (
    $1::UUID,
    $2::VARCHAR(80),
    $3::VARCHAR(32),
    $4::VARCHAR(80),
    $5::INT,
    $6::VARCHAR(32),
    $7::JSONB,
    1
)
ON CONFLICT (session_id) DO UPDATE
SET active_topic = EXCLUDED.active_topic,
    mode = EXCLUDED.mode,
    last_intent = EXCLUDED.last_intent,
    fallback_count = EXCLUDED.fallback_count,
    operator_status = EXCLUDED.operator_status,
    metadata = EXCLUDED.metadata,
    version = session_context.version + 1,
    updated_at = now()
RETURNING session_id, active_topic, mode, last_intent, fallback_count, operator_status, metadata, version, created_at, updated_at
`

type UpsertSessionContextParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	ActiveTopic    string      `json:"active_topic"`
	Mode           string      `json:"mode"`
	LastIntent     string      `json:"last_intent"`
	FallbackCount  int32       `json:"fallback_count"`
	OperatorStatus string      `json:"operator_status"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) UpsertSessionContext(ctx context.Context, arg UpsertSessionContextParams) (SessionContext, error) {
	row := q.db.QueryRow(ctx, upsertSessionContext,
		arg.SessionID,
		arg.ActiveTopic,
		arg.Mode,
		arg.LastIntent,
		arg.FallbackCount,
		arg.OperatorStatus,
		arg.Metadata,
	)
	var i SessionContext
	err := row.Scan(
		&i.SessionID,
		&i.ActiveTopic,
		&i.Mode,
		&i.LastIntent,
		&i.FallbackCount,
		&i.OperatorStatus,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
