// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConversationsByChannel = `-- name: CountConversationsByChannel :one
SELECT COUNT(*)::BIGINT FROM "conversations"
WHERE "channel" = $1::VARCHAR(50)
`

func (q *Queries) CountConversationsByChannel(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationsByChannel, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO "conversations" ("channel", "chat_id", "state", "version")
VALUES ($1::VARCHAR(50), $2::BIGINT, $3::VARCHAR(50), 1)
RETURNING id, channel, chat_id, state, version, created_at, updated_at
`

type CreateConversationParams struct {
	Column1 string `json:"column_1"`
	Column2 int64  `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Column1, arg.Column2, arg.Column3)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ChatID,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM "conversations"
WHERE "id" = $1::UUID
`

func (q *Queries) DeleteConversation(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, dollar_1)
	return err
}

const getConversationByChannelAndChatID = `-- name: GetConversationByChannelAndChatID :one
SELECT id, channel, chat_id, state, version, created_at, updated_at FROM "conversations"
WHERE "channel" = $1::VARCHAR(50)
  AND "chat_id" = $2::BIGINT
ORDER BY "created_at" DESC
LIMIT 1
`

type GetConversationByChannelAndChatIDParams struct {
	Column1 string `json:"column_1"`
	Column2 int64  `json:"column_2"`
}

func (q *Queries) GetConversationByChannelAndChatID(ctx context.Context, arg GetConversationByChannelAndChatIDParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByChannelAndChatID, arg.Column1, arg.Column2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ChatID,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, channel, chat_id, state, version, created_at, updated_at FROM "conversations"
WHERE "id" = $1::UUID
`

func (q *Queries) GetConversationByID(ctx context.Context, dollar_1 pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, dollar_1)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ChatID,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByChannel = `-- name: ListConversationsByChannel :many
SELECT id, channel, chat_id, state, version, created_at, updated_at FROM "conversations"
WHERE "channel" = $1::VARCHAR(50)
ORDER BY "updated_at" DESC
LIMIT $2::INT OFFSET $3::INT
`

type ListConversationsByChannelParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
}

func (q *Queries) ListConversationsByChannel(ctx context.Context, arg ListConversationsByChannelParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByChannel, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.ChatID,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByState = `-- name: ListConversationsByState :many
SELECT id, channel, chat_id, state, version, created_at, updated_at FROM "conversations"
WHERE "state" = $1::VARCHAR(50)
ORDER BY "updated_at" DESC
LIMIT $2::INT OFFSET $3::INT
`

type ListConversationsByStateParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
}

func (q *Queries) ListConversationsByState(ctx context.Context, arg ListConversationsByStateParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByState, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.ChatID,
			&i.State,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationState = `-- name: UpdateConversationState :one
UPDATE "conversations"
SET "state" = $2::VARCHAR(50),
    "updated_at" = now()
WHERE "id" = $1::UUID
RETURNING id, channel, chat_id, state, version, created_at, updated_at
`

type UpdateConversationStateParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) UpdateConversationState(ctx context.Context, arg UpdateConversationStateParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationState, arg.Column1, arg.Column2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ChatID,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConversationWithVersion = `-- name: UpdateConversationWithVersion :one
UPDATE "conversations"
SET "state" = $2::VARCHAR(50),
    "version" = "version" + 1,
    "updated_at" = now()
WHERE "id" = $1::UUID
RETURNING id, channel, chat_id, state, version, created_at, updated_at
`

type UpdateConversationWithVersionParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) UpdateConversationWithVersion(ctx context.Context, arg UpdateConversationWithVersionParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversationWithVersion, arg.Column1, arg.Column2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.ChatID,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
