// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decisions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const logDecision = `-- name: LogDecision :one
INSERT INTO decision_logs (
    "session_id",
    "message_id",
    "intent",
    "state",
    "response_key",
    "confidence",
    "low_confidence",
    "candidates"
)
VALUES (
    $1::UUID,
    $2::UUID,
    $3::VARCHAR(80),
    $4::VARCHAR(50),
    $5::VARCHAR(80),
    $6::DOUBLE PRECISION,
    $7::BOOLEAN,
    $8::JSONB
)
RETURNING id, session_id, message_id, intent, state, response_key, confidence, low_confidence, candidates, created_at, fallback_reason, threshold
`

type LogDecisionParams struct {
	SessionID     pgtype.UUID `json:"session_id"`
	MessageID     pgtype.UUID `json:"message_id"`
	Intent        string      `json:"intent"`
	State         string      `json:"state"`
	ResponseKey   string      `json:"response_key"`
	Confidence    *float64    `json:"confidence"`
	LowConfidence bool        `json:"low_confidence"`
	Candidates    []byte      `json:"candidates"`
}

func (q *Queries) LogDecision(ctx context.Context, arg LogDecisionParams) (DecisionLog, error) {
	row := q.db.QueryRow(ctx, logDecision,
		arg.SessionID,
		arg.MessageID,
		arg.Intent,
		arg.State,
		arg.ResponseKey,
		arg.Confidence,
		arg.LowConfidence,
		arg.Candidates,
	)
	var i DecisionLog
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.Intent,
		&i.State,
		&i.ResponseKey,
		&i.Confidence,
		&i.LowConfidence,
		&i.Candidates,
		&i.CreatedAt,
		&i.FallbackReason,
		&i.Threshold,
	)
	return i, err
}
