// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*)::BIGINT FROM messages
WHERE "session_id" = $1::UUID
`

func (q *Queries) CountMessages(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages ("session_id", "sender_type", "text", "intent")
VALUES ($1::UUID, $2::VARCHAR(16), $3::TEXT, $4::VARCHAR(50))
RETURNING id, session_id, sender_type, text, intent, created_at, idempotency_key, detected_intent, confidence, metadata, created_by
`

type CreateMessageParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 string      `json:"column_4"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderType,
		&i.Text,
		&i.Intent,
		&i.CreatedAt,
		&i.IdempotencyKey,
		&i.DetectedIntent,
		&i.Confidence,
		&i.Metadata,
		&i.CreatedBy,
	)
	return i, err
}

const getLastMessagesBySessionID = `-- name: GetLastMessagesBySessionID :many
SELECT id, session_id, sender_type, text, intent, created_at, idempotency_key, detected_intent, confidence, metadata, created_by FROM messages
WHERE "session_id" = $1::UUID
ORDER BY "created_at" DESC
LIMIT $2::INT
`

type GetLastMessagesBySessionIDParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 int32       `json:"column_2"`
}

func (q *Queries) GetLastMessagesBySessionID(ctx context.Context, arg GetLastMessagesBySessionIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getLastMessagesBySessionID, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderType,
			&i.Text,
			&i.Intent,
			&i.CreatedAt,
			&i.IdempotencyKey,
			&i.DetectedIntent,
			&i.Confidence,
			&i.Metadata,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesBySessionID = `-- name: GetMessagesBySessionID :many
SELECT id, session_id, sender_type, text, intent, created_at, idempotency_key, detected_intent, confidence, metadata, created_by FROM messages
WHERE "session_id" = $1::UUID
ORDER BY "created_at" ASC
LIMIT $2::INT OFFSET $3::INT
`

type GetMessagesBySessionIDParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 int32       `json:"column_2"`
	Column3 int32       `json:"column_3"`
}

func (q *Queries) GetMessagesBySessionID(ctx context.Context, arg GetMessagesBySessionIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesBySessionID, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderType,
			&i.Text,
			&i.Intent,
			&i.CreatedAt,
			&i.IdempotencyKey,
			&i.DetectedIntent,
			&i.Confidence,
			&i.Metadata,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
