// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActionsLog struct {
	ID              pgtype.UUID      `json:"id"`
	SessionID       pgtype.UUID      `json:"session_id"`
	ActionType      string           `json:"action_type"`
	RequestPayload  []byte           `json:"request_payload"`
	ResponsePayload []byte           `json:"response_payload"`
	Error           *string          `json:"error"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Message struct {
	ID         pgtype.UUID      `json:"id"`
	SessionID  pgtype.UUID      `json:"session_id"`
	SenderType string           `json:"sender_type"`
	Text       string           `json:"text"`
	Intent     *string          `json:"intent"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID             pgtype.UUID      `json:"id"`
	ChatID         int64            `json:"chat_id"`
	UserID         pgtype.UUID      `json:"user_id"`
	Channel        string           `json:"channel"`
	ExternalUserID string           `json:"external_user_id"`
	ClientID       string           `json:"client_id"`
	State          string           `json:"state"`
	ActiveTopic    string           `json:"active_topic"`
	Summary        *string          `json:"summary"`
	Version        int32            `json:"version"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Mode           string           `json:"mode"`
	LastIntent     string           `json:"last_intent"`
	FallbackCount  int32            `json:"fallback_count"`
	OperatorStatus string           `json:"operator_status"`
	Metadata       []byte           `json:"metadata"`
}

type TransitionsLog struct {
	ID        pgtype.UUID      `json:"id"`
	SessionID pgtype.UUID      `json:"session_id"`
	FromState string           `json:"from_state"`
	ToState   string           `json:"to_state"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Event     string           `json:"event"`
	Reason    string           `json:"reason"`
}

type User struct {
	ID         pgtype.UUID      `json:"id"`
	ExternalID string           `json:"external_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
