// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID        pgtype.UUID      `json:"id"`
	Channel   string           `json:"channel"`
	ChatID    int64            `json:"chat_id"`
	State     string           `json:"state"`
	Version   int32            `json:"version"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Message struct {
	ID             pgtype.UUID      `json:"id"`
	ConversationID pgtype.UUID      `json:"conversation_id"`
	SenderType     string           `json:"sender_type"`
	Payload        []byte           `json:"payload"`
	Intent         *string          `json:"intent"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
