// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operators.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptOperatorQueueItem = `-- name: AcceptOperatorQueueItem :one
UPDATE operator_queue
SET status = 'accepted',
    assigned_operator_id = $1::TEXT,
    accepted_at = COALESCE(accepted_at, now()),
    updated_at = now()
WHERE id = $2::UUID
  AND status = 'waiting'
RETURNING id, session_id, user_id, status, reason, priority, assigned_operator_id, context_snapshot, created_at, updated_at, accepted_at, closed_at
`

type AcceptOperatorQueueItemParams struct {
	OperatorID string      `json:"operator_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) AcceptOperatorQueueItem(ctx context.Context, arg AcceptOperatorQueueItemParams) (OperatorQueue, error) {
	row := q.db.QueryRow(ctx, acceptOperatorQueueItem, arg.OperatorID, arg.ID)
	var i OperatorQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.Reason,
		&i.Priority,
		&i.AssignedOperatorID,
		&i.ContextSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ClosedAt,
	)
	return i, err
}

const closeOperatorAssignment = `-- name: CloseOperatorAssignment :exec
UPDATE operator_assignments
SET status = 'closed',
    released_at = COALESCE(released_at, now())
WHERE queue_id = $1::UUID
  AND status = 'accepted'
`

func (q *Queries) CloseOperatorAssignment(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, closeOperatorAssignment, dollar_1)
	return err
}

const closeOperatorQueueItem = `-- name: CloseOperatorQueueItem :one
UPDATE operator_queue
SET status = 'closed',
    closed_at = COALESCE(closed_at, now()),
    updated_at = now()
WHERE id = $1::UUID
  AND status IN ('waiting', 'accepted')
RETURNING id, session_id, user_id, status, reason, priority, assigned_operator_id, context_snapshot, created_at, updated_at, accepted_at, closed_at
`

func (q *Queries) CloseOperatorQueueItem(ctx context.Context, id pgtype.UUID) (OperatorQueue, error) {
	row := q.db.QueryRow(ctx, closeOperatorQueueItem, id)
	var i OperatorQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.Reason,
		&i.Priority,
		&i.AssignedOperatorID,
		&i.ContextSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createOperatorAssignment = `-- name: CreateOperatorAssignment :one
INSERT INTO operator_assignments (queue_id, operator_id, status)
VALUES (
    $1::UUID,
    $2::TEXT,
    'accepted'
)
RETURNING id, queue_id, operator_id, status, assigned_at, released_at
`

type CreateOperatorAssignmentParams struct {
	QueueID    pgtype.UUID `json:"queue_id"`
	OperatorID string      `json:"operator_id"`
}

func (q *Queries) CreateOperatorAssignment(ctx context.Context, arg CreateOperatorAssignmentParams) (OperatorAssignment, error) {
	row := q.db.QueryRow(ctx, createOperatorAssignment, arg.QueueID, arg.OperatorID)
	var i OperatorAssignment
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.OperatorID,
		&i.Status,
		&i.AssignedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const createOperatorEvent = `-- name: CreateOperatorEvent :one
INSERT INTO operator_events (
    queue_id,
    session_id,
    event_type,
    actor_type,
    actor_id,
    payload
)
VALUES (
    $1::UUID,
    $2::UUID,
    $3::VARCHAR(24),
    $4::VARCHAR(16),
    $5::TEXT,
    $6::JSONB
)
RETURNING id, queue_id, session_id, event_type, actor_type, actor_id, payload, created_at
`

type CreateOperatorEventParams struct {
	QueueID   pgtype.UUID `json:"queue_id"`
	SessionID pgtype.UUID `json:"session_id"`
	EventType string      `json:"event_type"`
	ActorType string      `json:"actor_type"`
	ActorID   string      `json:"actor_id"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) CreateOperatorEvent(ctx context.Context, arg CreateOperatorEventParams) (OperatorEvent, error) {
	row := q.db.QueryRow(ctx, createOperatorEvent,
		arg.QueueID,
		arg.SessionID,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.Payload,
	)
	var i OperatorEvent
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.SessionID,
		&i.EventType,
		&i.ActorType,
		&i.ActorID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createOperatorQueueItem = `-- name: CreateOperatorQueueItem :one
INSERT INTO operator_queue (
    id,
    session_id,
    user_id,
    reason,
    priority,
    context_snapshot
)
VALUES (
    $1::UUID,
    $2::UUID,
    $3::UUID,
    $4::VARCHAR(40),
    $5::INT,
    $6::JSONB
)
RETURNING id, session_id, user_id, status, reason, priority, assigned_operator_id, context_snapshot, created_at, updated_at, accepted_at, closed_at
`

type CreateOperatorQueueItemParams struct {
	ID              pgtype.UUID `json:"id"`
	SessionID       pgtype.UUID `json:"session_id"`
	UserID          pgtype.UUID `json:"user_id"`
	Reason          string      `json:"reason"`
	Priority        int32       `json:"priority"`
	ContextSnapshot []byte      `json:"context_snapshot"`
}

func (q *Queries) CreateOperatorQueueItem(ctx context.Context, arg CreateOperatorQueueItemParams) (OperatorQueue, error) {
	row := q.db.QueryRow(ctx, createOperatorQueueItem,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Reason,
		arg.Priority,
		arg.ContextSnapshot,
	)
	var i OperatorQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.Reason,
		&i.Priority,
		&i.AssignedOperatorID,
		&i.ContextSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOpenOperatorQueueBySession = `-- name: GetOpenOperatorQueueBySession :one
SELECT id, session_id, user_id, status, reason, priority, assigned_operator_id, context_snapshot, created_at, updated_at, accepted_at, closed_at FROM operator_queue
WHERE session_id = $1::UUID
  AND status IN ('waiting', 'accepted')
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetOpenOperatorQueueBySession(ctx context.Context, dollar_1 pgtype.UUID) (OperatorQueue, error) {
	row := q.db.QueryRow(ctx, getOpenOperatorQueueBySession, dollar_1)
	var i OperatorQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.Reason,
		&i.Priority,
		&i.AssignedOperatorID,
		&i.ContextSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOperatorQueueByID = `-- name: GetOperatorQueueByID :one
SELECT id, session_id, user_id, status, reason, priority, assigned_operator_id, context_snapshot, created_at, updated_at, accepted_at, closed_at FROM operator_queue
WHERE id = $1::UUID
`

func (q *Queries) GetOperatorQueueByID(ctx context.Context, dollar_1 pgtype.UUID) (OperatorQueue, error) {
	row := q.db.QueryRow(ctx, getOperatorQueueByID, dollar_1)
	var i OperatorQueue
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Status,
		&i.Reason,
		&i.Priority,
		&i.AssignedOperatorID,
		&i.ContextSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listOperatorQueueByStatus = `-- name: ListOperatorQueueByStatus :many
SELECT id, session_id, user_id, status, reason, priority, assigned_operator_id, context_snapshot, created_at, updated_at, accepted_at, closed_at FROM operator_queue
WHERE status = $1::VARCHAR(16)
ORDER BY created_at ASC
LIMIT $2::INT OFFSET $3::INT
`

type ListOperatorQueueByStatusParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
}

func (q *Queries) ListOperatorQueueByStatus(ctx context.Context, arg ListOperatorQueueByStatusParams) ([]OperatorQueue, error) {
	rows, err := q.db.Query(ctx, listOperatorQueueByStatus, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperatorQueue{}
	for rows.Next() {
		var i OperatorQueue
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Status,
			&i.Reason,
			&i.Priority,
			&i.AssignedOperatorID,
			&i.ContextSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOperator = `-- name: UpsertOperator :one
INSERT INTO operators (operator_id, fixture_id, display_name, status)
VALUES (
    $1::TEXT,
    $2::TEXT,
    $3::TEXT,
    $4::VARCHAR(16)
)
ON CONFLICT (operator_id) DO UPDATE
SET fixture_id = EXCLUDED.fixture_id,
    display_name = EXCLUDED.display_name,
    status = EXCLUDED.status,
    updated_at = now()
RETURNING operator_id, fixture_id, display_name, status, created_at, updated_at
`

type UpsertOperatorParams struct {
	OperatorID  string `json:"operator_id"`
	FixtureID   string `json:"fixture_id"`
	DisplayName string `json:"display_name"`
	Status      string `json:"status"`
}

func (q *Queries) UpsertOperator(ctx context.Context, arg UpsertOperatorParams) (Operator, error) {
	row := q.db.QueryRow(ctx, upsertOperator,
		arg.OperatorID,
		arg.FixtureID,
		arg.DisplayName,
		arg.Status,
	)
	var i Operator
	err := row.Scan(
		&i.OperatorID,
		&i.FixtureID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
