// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CloseSession(ctx context.Context, dollar_1 pgtype.UUID) (Session, error)
	CountActions(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	CountMessages(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	CountSessions(ctx context.Context) (int64, error)
	CountTransitions(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, dollar_1 string) (User, error)
	DeleteSession(ctx context.Context, dollar_1 pgtype.UUID) error
	GetActionsBySessionID(ctx context.Context, arg GetActionsBySessionIDParams) ([]ActionsLog, error)
	GetActionsByType(ctx context.Context, arg GetActionsByTypeParams) ([]ActionsLog, error)
	GetLastMessagesBySessionID(ctx context.Context, arg GetLastMessagesBySessionIDParams) ([]Message, error)
	GetMessagesBySessionID(ctx context.Context, arg GetMessagesBySessionIDParams) ([]Message, error)
	GetSessionByChatID(ctx context.Context, dollar_1 int64) (Session, error)
	GetSessionByID(ctx context.Context, dollar_1 pgtype.UUID) (Session, error)
	GetTransitionsBySessionID(ctx context.Context, arg GetTransitionsBySessionIDParams) ([]TransitionsLog, error)
	GetUserByExternalID(ctx context.Context, dollar_1 string) (User, error)
	GetUserByID(ctx context.Context, dollar_1 pgtype.UUID) (User, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	ListSessionsByState(ctx context.Context, arg ListSessionsByStateParams) ([]Session, error)
	ListSessionsByStatus(ctx context.Context, arg ListSessionsByStatusParams) ([]Session, error)
	ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LogAction(ctx context.Context, arg LogActionParams) (ActionsLog, error)
	LogTransition(ctx context.Context, arg LogTransitionParams) (TransitionsLog, error)
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (Session, error)
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error)
	UpdateSessionSummary(ctx context.Context, arg UpdateSessionSummaryParams) (Session, error)
	UpdateSessionWithVersion(ctx context.Context, arg UpdateSessionWithVersionParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
