// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptOperatorQueueItem(ctx context.Context, arg AcceptOperatorQueueItemParams) (OperatorQueue, error)
	CloseOperatorAssignment(ctx context.Context, dollar_1 pgtype.UUID) error
	CloseOperatorQueueItem(ctx context.Context, id pgtype.UUID) (OperatorQueue, error)
	CloseSession(ctx context.Context, dollar_1 pgtype.UUID) (Session, error)
	CountActions(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	CountMessages(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	CountSessions(ctx context.Context) (int64, error)
	CountTransitions(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageEvent(ctx context.Context, arg CreateMessageEventParams) (MessageEvent, error)
	CreateOperatorAssignment(ctx context.Context, arg CreateOperatorAssignmentParams) (OperatorAssignment, error)
	CreateOperatorEvent(ctx context.Context, arg CreateOperatorEventParams) (OperatorEvent, error)
	CreateOperatorQueueItem(ctx context.Context, arg CreateOperatorQueueItemParams) (OperatorQueue, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, dollar_1 string) (User, error)
	DeleteSession(ctx context.Context, dollar_1 pgtype.UUID) error
	FindDemoAccountByIdentifier(ctx context.Context, identifier string) (DemoAccount, error)
	FindDemoBookingByIdentifier(ctx context.Context, identifier string) (DemoBooking, error)
	FindDemoPaymentByIdentifier(ctx context.Context, identifier string) (DemoPayment, error)
	FindDemoWorkspaceBookingByIdentifier(ctx context.Context, identifier string) (DemoWorkspaceBooking, error)
	GetActionsBySessionID(ctx context.Context, arg GetActionsBySessionIDParams) ([]ActionsLog, error)
	GetActionsByType(ctx context.Context, arg GetActionsByTypeParams) ([]ActionsLog, error)
	GetActiveSessionByIdentity(ctx context.Context, arg GetActiveSessionByIdentityParams) (Session, error)
	GetIntentByKey(ctx context.Context, dollar_1 string) (Intent, error)
	GetLastMessagesBySessionID(ctx context.Context, arg GetLastMessagesBySessionIDParams) ([]Message, error)
	GetMessageEventByExternalID(ctx context.Context, arg GetMessageEventByExternalIDParams) (MessageEvent, error)
	GetMessagesBySessionID(ctx context.Context, arg GetMessagesBySessionIDParams) ([]Message, error)
	GetOpenOperatorQueueBySession(ctx context.Context, dollar_1 pgtype.UUID) (OperatorQueue, error)
	GetOperatorQueueByID(ctx context.Context, dollar_1 pgtype.UUID) (OperatorQueue, error)
	GetSessionByID(ctx context.Context, dollar_1 pgtype.UUID) (Session, error)
	GetSessionContext(ctx context.Context, dollar_1 pgtype.UUID) (SessionContext, error)
	GetTransitionsBySessionID(ctx context.Context, arg GetTransitionsBySessionIDParams) ([]TransitionsLog, error)
	GetUserByExternalID(ctx context.Context, dollar_1 string) (User, error)
	GetUserByID(ctx context.Context, dollar_1 pgtype.UUID) (User, error)
	ListActiveIntents(ctx context.Context) ([]Intent, error)
	ListDecisionCandidates(ctx context.Context, dollar_1 pgtype.UUID) ([]DecisionCandidate, error)
	ListOperatorQueueByStatus(ctx context.Context, arg ListOperatorQueueByStatusParams) ([]OperatorQueue, error)
	ListQuickRepliesByIntent(ctx context.Context, dollar_1 pgtype.UUID) ([]QuickReply, error)
	ListQuickRepliesByResponseKey(ctx context.Context, dollar_1 string) ([]QuickReply, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	ListSessionsByState(ctx context.Context, arg ListSessionsByStateParams) ([]Session, error)
	ListSessionsByStatus(ctx context.Context, arg ListSessionsByStatusParams) ([]Session, error)
	ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LogAction(ctx context.Context, arg LogActionParams) (ActionsLog, error)
	LogDecision(ctx context.Context, arg LogDecisionParams) (DecisionLog, error)
	LogDecisionCandidate(ctx context.Context, arg LogDecisionCandidateParams) (DecisionCandidate, error)
	LogTransition(ctx context.Context, arg LogTransitionParams) (TransitionsLog, error)
	SearchIntentExamples(ctx context.Context, arg SearchIntentExamplesParams) ([]SearchIntentExamplesRow, error)
	SearchKnowledgeChunks(ctx context.Context, arg SearchKnowledgeChunksParams) ([]SearchKnowledgeChunksRow, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (Session, error)
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error)
	UpdateSessionWithVersion(ctx context.Context, arg UpdateSessionWithVersionParams) (Session, error)
	UpsertDemoAccount(ctx context.Context, arg UpsertDemoAccountParams) (DemoAccount, error)
	UpsertDemoBooking(ctx context.Context, arg UpsertDemoBookingParams) (DemoBooking, error)
	UpsertDemoPayment(ctx context.Context, arg UpsertDemoPaymentParams) (DemoPayment, error)
	UpsertDemoWorkspaceBooking(ctx context.Context, arg UpsertDemoWorkspaceBookingParams) (DemoWorkspaceBooking, error)
	UpsertIntent(ctx context.Context, arg UpsertIntentParams) (Intent, error)
	UpsertIntentExample(ctx context.Context, arg UpsertIntentExampleParams) (UpsertIntentExampleRow, error)
	UpsertKnowledgeArticle(ctx context.Context, arg UpsertKnowledgeArticleParams) (KnowledgeArticle, error)
	UpsertKnowledgeChunk(ctx context.Context, arg UpsertKnowledgeChunkParams) (UpsertKnowledgeChunkRow, error)
	UpsertOperator(ctx context.Context, arg UpsertOperatorParams) (Operator, error)
	UpsertQuickReply(ctx context.Context, arg UpsertQuickReplyParams) (QuickReply, error)
	UpsertSessionContext(ctx context.Context, arg UpsertSessionContextParams) (SessionContext, error)
}

var _ Querier = (*Queries)(nil)
