// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountConversationsByChannel(ctx context.Context, dollar_1 string) (int64, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	DeleteConversation(ctx context.Context, dollar_1 pgtype.UUID) error
	GetConversationByChannelAndChatID(ctx context.Context, arg GetConversationByChannelAndChatIDParams) (Conversation, error)
	GetConversationByID(ctx context.Context, dollar_1 pgtype.UUID) (Conversation, error)
	ListConversationsByChannel(ctx context.Context, arg ListConversationsByChannelParams) ([]Conversation, error)
	ListConversationsByState(ctx context.Context, arg ListConversationsByStateParams) ([]Conversation, error)
	UpdateConversationState(ctx context.Context, arg UpdateConversationStateParams) (Conversation, error)
	UpdateConversationWithVersion(ctx context.Context, arg UpdateConversationWithVersionParams) (Conversation, error)
}

var _ Querier = (*Queries)(nil)
