// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeSession = `-- name: CloseSession :one
UPDATE "sessions"
SET "status" = 'closed',
    "updated_at" = now()
WHERE "id" = $1::UUID
RETURNING id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at
`

func (q *Queries) CloseSession(ctx context.Context, dollar_1 pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, closeSession, dollar_1)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*)::BIGINT FROM "sessions"
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO "sessions" (
    "chat_id",
    "user_id",
    "channel",
    "external_user_id",
    "client_id",
    "state",
    "active_topic",
    "version",
    "status"
)
VALUES (
    $1::BIGINT,
    $2::UUID,
    $3::TEXT,
    $4::TEXT,
    $5::TEXT,
    $6::VARCHAR(50),
    $7::VARCHAR(50),
    1,
    'active'
)
RETURNING id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at
`

type CreateSessionParams struct {
	ChatID         int64       `json:"chat_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Channel        string      `json:"channel"`
	ExternalUserID string      `json:"external_user_id"`
	ClientID       string      `json:"client_id"`
	State          string      `json:"state"`
	ActiveTopic    string      `json:"active_topic"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ChatID,
		arg.UserID,
		arg.Channel,
		arg.ExternalUserID,
		arg.ClientID,
		arg.State,
		arg.ActiveTopic,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM "sessions"
WHERE "id" = $1::UUID
`

func (q *Queries) DeleteSession(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, dollar_1)
	return err
}

const getActiveSessionByIdentity = `-- name: GetActiveSessionByIdentity :one
SELECT id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at FROM "sessions"
WHERE "channel" = $1::TEXT
  AND "status" = 'active'
  AND (
      ($2::TEXT <> '' AND "external_user_id" = $2::TEXT)
      OR ($2::TEXT = '' AND "client_id" = $3::TEXT)
  )
ORDER BY "created_at" DESC
LIMIT 1
`

type GetActiveSessionByIdentityParams struct {
	Channel        string `json:"channel"`
	ExternalUserID string `json:"external_user_id"`
	ClientID       string `json:"client_id"`
}

func (q *Queries) GetActiveSessionByIdentity(ctx context.Context, arg GetActiveSessionByIdentityParams) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByIdentity, arg.Channel, arg.ExternalUserID, arg.ClientID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByChatID = `-- name: GetSessionByChatID :one
SELECT id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at FROM "sessions"
WHERE "chat_id" = $1::BIGINT
ORDER BY "created_at" DESC
LIMIT 1
`

func (q *Queries) GetSessionByChatID(ctx context.Context, dollar_1 int64) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByChatID, dollar_1)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at FROM "sessions"
WHERE "id" = $1::UUID
`

func (q *Queries) GetSessionByID(ctx context.Context, dollar_1 pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, dollar_1)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at FROM "sessions"
ORDER BY "updated_at" DESC
LIMIT $1::INT OFFSET $2::INT
`

type ListSessionsParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.Channel,
			&i.ExternalUserID,
			&i.ClientID,
			&i.State,
			&i.ActiveTopic,
			&i.Summary,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByState = `-- name: ListSessionsByState :many
SELECT id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at FROM "sessions"
WHERE "state" = $1::VARCHAR(50)
ORDER BY "updated_at" DESC
LIMIT $2::INT OFFSET $3::INT
`

type ListSessionsByStateParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
}

func (q *Queries) ListSessionsByState(ctx context.Context, arg ListSessionsByStateParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByState, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.Channel,
			&i.ExternalUserID,
			&i.ClientID,
			&i.State,
			&i.ActiveTopic,
			&i.Summary,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByStatus = `-- name: ListSessionsByStatus :many
SELECT id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at FROM "sessions"
WHERE "status" = $1::VARCHAR(20)
ORDER BY "updated_at" DESC
LIMIT $2::INT OFFSET $3::INT
`

type ListSessionsByStatusParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 int32  `json:"column_3"`
}

func (q *Queries) ListSessionsByStatus(ctx context.Context, arg ListSessionsByStatusParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByStatus, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.Channel,
			&i.ExternalUserID,
			&i.ClientID,
			&i.State,
			&i.ActiveTopic,
			&i.Summary,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at FROM "sessions"
WHERE "user_id" = $1::UUID
ORDER BY "updated_at" DESC
LIMIT $2::INT OFFSET $3::INT
`

type ListSessionsByUserParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 int32       `json:"column_2"`
	Column3 int32       `json:"column_3"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.Channel,
			&i.ExternalUserID,
			&i.ClientID,
			&i.State,
			&i.ActiveTopic,
			&i.Summary,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE "sessions"
SET "state" = $1::VARCHAR(50),
    "active_topic" = $2::VARCHAR(50),
    "updated_at" = now()
WHERE "id" = $3::UUID
RETURNING id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at
`

type UpdateSessionParams struct {
	State       string      `json:"state"`
	ActiveTopic string      `json:"active_topic"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSession, arg.State, arg.ActiveTopic, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionState = `-- name: UpdateSessionState :one
UPDATE "sessions"
SET "state" = $2::VARCHAR(50),
    "updated_at" = now()
WHERE "id" = $1::UUID
RETURNING id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at
`

type UpdateSessionStateParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) UpdateSessionState(ctx context.Context, arg UpdateSessionStateParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionState, arg.Column1, arg.Column2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE "sessions"
SET "status" = $2::VARCHAR(20),
    "updated_at" = now()
WHERE "id" = $1::UUID
RETURNING id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at
`

type UpdateSessionStatusParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionStatus, arg.Column1, arg.Column2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionSummary = `-- name: UpdateSessionSummary :one
UPDATE "sessions"
SET "summary" = $2::VARCHAR(255),
    "updated_at" = now()
WHERE "id" = $1::UUID
RETURNING id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at
`

type UpdateSessionSummaryParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) UpdateSessionSummary(ctx context.Context, arg UpdateSessionSummaryParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionSummary, arg.Column1, arg.Column2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionWithVersion = `-- name: UpdateSessionWithVersion :one
UPDATE "sessions"
SET "state" = $2::VARCHAR(50),
    "version" = "version" + 1,
    "updated_at" = now()
WHERE "id" = $1::UUID
RETURNING id, chat_id, user_id, channel, external_user_id, client_id, state, active_topic, summary, version, status, created_at, updated_at
`

type UpdateSessionWithVersionParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
}

func (q *Queries) UpdateSessionWithVersion(ctx context.Context, arg UpdateSessionWithVersionParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionWithVersion, arg.Column1, arg.Column2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Channel,
		&i.ExternalUserID,
		&i.ClientID,
		&i.State,
		&i.ActiveTopic,
		&i.Summary,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
