// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transitions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransitions = `-- name: CountTransitions :one
SELECT COUNT(*)::BIGINT FROM transitions_log
WHERE "session_id" = $1::UUID
`

func (q *Queries) CountTransitions(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTransitions, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTransitionsBySessionID = `-- name: GetTransitionsBySessionID :many
SELECT id, session_id, from_state, to_state, event, reason, created_at FROM transitions_log
WHERE "session_id" = $1::UUID
ORDER BY "created_at" DESC
LIMIT $2::INT OFFSET $3::INT
`

type GetTransitionsBySessionIDParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 int32       `json:"column_2"`
	Column3 int32       `json:"column_3"`
}

func (q *Queries) GetTransitionsBySessionID(ctx context.Context, arg GetTransitionsBySessionIDParams) ([]TransitionsLog, error) {
	rows, err := q.db.Query(ctx, getTransitionsBySessionID, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransitionsLog{}
	for rows.Next() {
		var i TransitionsLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FromState,
			&i.ToState,
			&i.Event,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logTransition = `-- name: LogTransition :one
INSERT INTO transitions_log ("session_id", "from_state", "to_state", "event", "reason")
VALUES ($1::UUID, $2::VARCHAR(50), $3::VARCHAR(50), $4::VARCHAR(64), $5::TEXT)
RETURNING id, session_id, from_state, to_state, event, reason, created_at
`

type LogTransitionParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Column4 string      `json:"column_4"`
	Column5 string      `json:"column_5"`
}

func (q *Queries) LogTransition(ctx context.Context, arg LogTransitionParams) (TransitionsLog, error) {
	row := q.db.QueryRow(ctx, logTransition,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i TransitionsLog
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FromState,
		&i.ToState,
		&i.Event,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}
