// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::BIGINT FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users ("external_id")
VALUES ($1::TEXT)
ON CONFLICT ("external_id") DO NOTHING
RETURNING id, external_id, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, dollar_1 string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, created_at, updated_at FROM users
WHERE "external_id" = $1::TEXT
`

func (q *Queries) GetUserByExternalID(ctx context.Context, dollar_1 string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_id, created_at, updated_at FROM users
WHERE "id" = $1::UUID
`

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, external_id, created_at, updated_at FROM users
ORDER BY "created_at" DESC
LIMIT $1::INT OFFSET $2::INT
`

type ListUsersParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
